name: build-image

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Run Semantic Release
        run: |
          npm ci
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  release:
    needs:
      - semantic-release
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Run Gradle Jib
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: jib
  update-kustomize:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Get version
        run: |
          file="./gradle.properties"
          value=$(grep version ${file} | cut -d' ' -f3)
          echo "app_version=$value" >> $GITHUB_ENV
      - name: Checkout Kustomize
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: zlaval-elte-thesis/deployment
          ref: master
      - name: Set Image
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.24.0
          kustomize: 4.5.4
          command: |
            cd base
            kustomize edit set image zalerix/thesis-quiz-service:latest=zalerix/thesis-quiz-service:${{ env.app_version }}
            git config --global user.email "zlaval@gmail.com"
            git config --global user.name "CI bot"
            git add .
            git commit -m "build: update quiz-service image tag to ${{ env.app_version }}"
            git push
