apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  template:
    spec:
      containers:
        - name: auth-service
          volumeMounts:
            - mountPath: /data
              name: auth-store
      volumes:
        - name: auth-store
          persistentVolumeClaim:
            claimName: auth-store-pvc