apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      name: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0.4
          ports:
            - containerPort: 27017
              name: port
          resources:
           requests:
              cpu: "200m"
              memory: "384Mi"
           limits:
              cpu: "300m"
              memory: "384Mi"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin123
            - name: MONGO_INITDB_DATABASE
              value: admin