apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-url
spec:
  type: ClusterIP
  ports:
    - name: rabbitmq-port
      port: 5672
      targetPort: 5672
    - name: rabbitmq-admin-port
      port: 15672
      targetPort: 15672
  selector:
    name: rabbitmq