management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
spring:
  boot:
    admin.client.url: http://spring-admin:8080
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:10000"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: video-route
          uri: http://video-service:8080
          predicates:
            - Path=/video/**
          filters:
            - RewritePath=/video/?(?<segment>.*), /$\{segment}
        - id: auth-route
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
        - id: subject-route
          uri: http://subject-service:8080
          predicates:
            - Path=/subject/**
          filters:
            - RewritePath=/subject/?(?<segment>.*), /$\{segment}
        - id: quiz-route
          uri: http://quiz-service:8080
          predicates:
            - Path=/quiz/**
          filters:
            - RewritePath=/quiz/?(?<segment>.*), /$\{segment}
        - id: grade-route
          uri: http://grade-service:8080
          predicates:
            - Path=/grade/**
          filters:
            - RewritePath=/grade/?(?<segment>.*), /$\{segment}
        - id: enrollment-route
          uri: http://enrollment-service:8080
          predicates:
            - Path=/enrollment/**
          filters:
            - RewritePath=/enrollment/?(?<segment>.*), /$\{segment}
        - id: notification-route
          uri: http://notification-service:8080
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/?(?<segment>.*), /$\{segment}