management:
  server:
    port: 9003
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
spring:
  boot:
    admin.client.url: http://localhost:9115
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017
server:
  port: 8003
jwt:
  validity-in-minutes: 181588461183
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: debug