apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
spec:
  template:
    spec:
      containers:
        - name: notification-service
          livenessProbe:
            initialDelaySeconds: 120
            failureThreshold: 5
          readinessProbe:
            initialDelaySeconds: 130
            failureThreshold: 5
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "300m"
              memory: "512Mi"