apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-service-deployment
spec:
  selector:
    matchLabels:
      name: grade-service
  template:
    metadata:
      labels:
        name: grade-service
    spec:
      containers:
        - name: grade-service
          image: zalerix/thesis-grade-service:latest
          livenessProbe:
            initialDelaySeconds: 5
            failureThreshold: 5
            httpGet:
              port: 9000
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 5
            httpGet:
              port: 9000
              path: /actuator/health/readiness
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "300m"
              memory: "1Gi"
          ports:
            - containerPort: 8080
              name: app-port
            - containerPort: 9000
              name: actuator-port
          envFrom:
            - configMapRef:
                  name: common-properties
            - secretRef:
                name: common-secrets