name: Master merge workflow

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Run Semantic Release
        run: |
          npm ci
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  release:
    needs:
      - semantic-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Get version
        run: |
          value=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)
          echo "app_version=$value" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: |
            zalerix/thesis-knowhere-vui:${{ env.app_version }}
            zalerix/thesis-knowhere-vui:latest
  update-kustomize:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Get version
        run: |
          value=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)
          echo "app_version=$value" >> $GITHUB_ENV
      - name: Checkout Kustomize
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: zlaval-elte-thesis/deployment
          ref: master
      - name: Set Image
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.24.0
          kustomize: 4.5.4
          command: |
            cd base
            kustomize edit set image zalerix/thesis-knowhere-vui:latest=zalerix/thesis-knowhere-vui:${{ env.app_version }}
            git config --global user.email "zlaval@gmail.com"
            git config --global user.name "CI bot"
            git add .
            git commit -m "build: update knowhere-vui image tag to ${{ env.app_version }}"
            git push
