management:
  server:
    port: 9000
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    binders:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: grade-service
    enable:
      all: true
  tracing:
    enabled: true
    baggage:
      enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-url:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name:},tenant_id=%mdc{tenantId} trace_id=%mdc{traceId} span_id=%mdc{spanId}]"
  level:
    root: info
server:
  shutdown: graceful
spring:
  boot:
    admin.client.url: http://spring-admin-url:8080
  application:
    name: grade-service
  jackson:
    mapper:
      default-view-inclusion: true
  jmx:
    enabled: false
  data:
    mongodb:
      uri: mongodb://admin:admin123@mongodb-url:27017
      database: grade
      auto-index-creation: true
  rabbitmq:
    username: admin
    password: admin123
    host: rabbitmq-url
    port: 5672
jwt:
  secret-key: aklsdh983zrhalfnb;iou*rqw/234>asdfa
mongock:
  enabled: false
resilience4j:
  circuitbreaker:
    instances:
      auth:
        registerHealthIndicator: true
      subject:
        registerHealthIndicator: true
  bulkhead:
    instances:
      auth:
        maxConcurrentCalls: 20
        maxWaitDuration: 500ms
      subject:
        maxWaitDuration: 1s
        maxConcurrentCalls: 15
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: true
        limitForPeriod: 100
        limitRefreshPeriod: 1
        timeoutDuration: 10ms
        eventConsumerBufferSize: 100
    instances:
      auth:
        baseConfig: default
      subject:
        baseConfig: default
knowhere:
  service:
    auth: http://auth-service-url:8080
    subject: http://subject-service-url:8080


