apiVersion: v1
kind: Service
metadata:
  name: subject-service-url
spec:
  type: ClusterIP
  ports:
    - name: app-port
      port: 8080
      targetPort: 8080
    - name: monitoring-port
      port: 9000
      targetPort: 9000
  selector:
    name: subject-service