apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  template:
    spec:
      containers:
        - name: mongodb
          volumeMounts:
            - mountPath: /data/db
              name: mongo-store
      volumes:
        - name: mongo-store
          persistentVolumeClaim:
            claimName: mongo-pvc