apiVersion: v1
kind: Service
metadata:
  name: video-service-url
spec:
  type: ClusterIP
  ports:
    - name: app-port
      port: 8080
      targetPort: 8080
    - name: monitoring-port
      port: 9000
      targetPort: 9000
    - name: debug-port
      port: 5005
      targetPort: 5005
  selector:
     name: video-service