management:
  server:
    port: 9000
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    binders:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: subject-service
    enable:
      all: true
  tracing:
    enabled: true
    baggage:
      enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-url:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name:},tenant_id=%mdc{tenantId} trace_id=%mdc{traceId} span_id=%mdc{spanId}]"
  level:
    root: info
server:
  shutdown: graceful
jwt:
  secret-key: aklsdh983zrhalfnb;iou*rqw/234>asdfa
spring:
  boot:
    admin.client.url: http://spring-admin-url:8080
  application:
    name: subject-service
  jackson:
    mapper:
      default-view-inclusion: true
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgres-url:5432/postgres
    username: admin
    password: admin123
  rabbitmq:
    username: admin
    password: admin123
    host: rabbitmq-url
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
resilience4j:
  circuitbreaker:
    instances:
      enrollment:
        registerHealthIndicator: true
      grade:
        registerHealthIndicator: true
      quiz:
        registerHealthIndicator: true
knowhere:
  service:
    enrollment: http://enrollment-service-url:8080
    grade: http://grade-service-url:8080
    quiz: http://quiz-service-url:8080
  scheduling:
    enabled: true


